services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    ports:
      - "5432:5432" # Host port:Container port
    volumes:
     - ./services/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password123

  s3:
    image: localstack/localstack:s3-latest
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
      # - PERSIST_DEFAULT=0
      # - PERSIST_S3=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  services-init:
    image: python:3.11
    depends_on:
      - db
      - s3
    volumes:
      - ./services/setup:/setup
    command: >
      bash -c "pip install -r /setup/requirements.txt && python /setup/main.py"
    # Prevent restarts and simulate --rm
    restart: "no"